"""empty message

Revision ID: 18035edfb86c
Revises: a8f3ba06344c
Create Date: 2020-12-09 01:28:01.971081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18035edfb86c'
down_revision = 'a8f3ba06344c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
