"""empty message

Revision ID: 3b2d089495f4
Revises: f90cccf654a2
Create Date: 2020-12-09 11:29:36.990142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2d089495f4'
down_revision = 'f90cccf654a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p2rconn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p2rconn', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
