"""empty message

Revision ID: 8565de1eef8b
Revises: db1ad2a18e55
Create Date: 2020-12-05 16:42:06.219559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8565de1eef8b'
down_revision = 'db1ad2a18e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk":
        "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('message', schema=None, naming_convention = naming_convention) as batch_op:
        batch_op.drop_constraint('fk_message_room_id_User', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_room_id_room'), 'room', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_room_id_room'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['room_id'], ['id'])

    # ### end Alembic commands ###
