"""empty message

Revision ID: a8f3ba06344c
Revises: 8565de1eef8b
Create Date: 2020-12-08 22:59:35.601358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f3ba06344c'
down_revision = '8565de1eef8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['User.id'], name=op.f('fk_invitation_guest_id_User')),
    sa.ForeignKeyConstraint(['host_id'], ['User.id'], name=op.f('fk_invitation_host_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation'))
    )
    op.create_table('receivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_receivers_message_id_message')),
    sa.ForeignKeyConstraint(['receiver_id'], ['User.id'], name=op.f('fk_receivers_receiver_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receivers'))
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index('ix_room_roomname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index('ix_room_roomname', ['roomname'], unique=1)

    op.drop_table('receivers')
    op.drop_table('invitation')
    # ### end Alembic commands ###
