"""empty message

Revision ID: c69eef5ffde0
Revises: e99fd60dbd08
Create Date: 2020-12-02 15:02:37.251487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69eef5ffde0'
down_revision = 'e99fd60dbd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_message_sender_id_User'), 'User', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_sender_id_User'), type_='foreignkey')

    # ### end Alembic commands ###
