"""empty message

Revision ID: cd81445b848b
Revises: c69eef5ffde0
Create Date: 2020-12-05 02:57:12.843357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd81445b848b'
down_revision = 'c69eef5ffde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2pconn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['User.id'], name=op.f('fk_p2pconn_user1_id_User')),
    sa.ForeignKeyConstraint(['user2_id'], ['User.id'], name=op.f('fk_p2pconn_user2_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_p2pconn')),
    sa.UniqueConstraint('user1_id', 'user2_id', name='p2p_connection')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roomname', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['User.id'], name=op.f('fk_room_creator_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('roomname', name=op.f('uq_room_roomname'))
    )
    op.create_table('p2rconn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['User.id'], name=op.f('fk_p2rconn_room_id_User')),
    sa.ForeignKeyConstraint(['user_id'], ['room.id'], name=op.f('fk_p2rconn_user_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_p2rconn')),
    sa.UniqueConstraint('user_id', 'room_id', name='p2r_connection')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_message_room_id_User'), 'User', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_room_id_User'), type_='foreignkey')
        batch_op.drop_column('room_id')

    op.drop_table('p2rconn')
    op.drop_table('room')
    op.drop_table('p2pconn')
    # ### end Alembic commands ###
