"""empty message

Revision ID: db1ad2a18e55
Revises: cd81445b848b
Create Date: 2020-12-05 16:22:22.633769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1ad2a18e55'
down_revision = 'cd81445b848b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=True)
        batch_op.drop_constraint('uq_User_email', type_='unique')
        batch_op.drop_constraint('uq_User_username', type_='unique')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_roomname'), ['roomname'], unique=True)
        batch_op.drop_constraint('uq_room_roomname', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_room_roomname', ['roomname'])
        batch_op.drop_index(batch_op.f('ix_room_roomname'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_User_username', ['username'])
        batch_op.create_unique_constraint('uq_User_email', ['email'])
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    # ### end Alembic commands ###
