"""empty message

Revision ID: f90cccf654a2
Revises: 18035edfb86c
Create Date: 2020-12-09 02:22:49.748168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90cccf654a2'
down_revision = '18035edfb86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_invitation_room_id_room'), 'room', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invitation_room_id_room'), type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
